// 这里是抽奖的人员名单
let niceShot = [
    {"name": "奖励A"},
    {"name": "奖励B"},
    {"name": "奖励C"},
    {"name": "奖励D"},
    {"name": "奖励E"},
    {"name": "奖励F"},
    {"name": "奖励G"},
    {"name": "奖励H"},
    {"name": "奖励I"},
    {"name": "奖励J"},
    {"name": "奖励K"},
    {"name": "奖励L"},
    {"name": "奖励M"},
    {"name": "奖励N"},
    {"name": "奖励O"},
    {"name": "奖励P"},
    {"name": "奖励Q"},
    {"name": "奖励R"},
    {"name": "奖励S"},
    {"name": "奖励T"},
    {"name": "奖励O"},
    {"name": "奖励P"},
    {"name": "奖励Q"},
    {"name": "奖励R"},
    {"name": "奖励R"},
    {"name": "奖励S"},
    {"name": "奖励T"},
    {"name": "奖励U"},
    {"name": "奖励V"},
    {"name": "奖励W"},
    {"name": "奖励X"},
    {"name": "奖励Y"},
    {"name": "奖励Z"},
]


export default niceShot
